import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import AppRewards from './AppRewards'
import { readPendingRedemption, savePendingRedemption } from '../lib/redemptionRecovery'

const api = vi.hoisted(() => ({ getRewards: vi.fn(), redeemReward: vi.fn(), getRewardHistory: vi.fn() }))
vi.mock('../lib/userData', () => api)
vi.mock('../auth/AuthContext', () => ({ useAuth: () => ({ user: { id: 'user-a' } }) }))
vi.mock('../components/app/AppNav', () => ({ default: () => null }))
vi.mock('../components/PageShell', () => ({ default: ({ children }) => <main>{children}</main> }))
const wallet = { account: { available_points: 100, lifetime_points: 100 }, transactions: [], rewards: [{ id: 'perk-1', title: 'Museum perk', points_cost: 25, inventory: 2 }] }

beforeEach(() => {
  localStorage.clear()
  vi.restoreAllMocks()
  api.getRewards.mockReset().mockResolvedValue(wallet)
  api.redeemReward.mockReset().mockResolvedValue('receipt-1')
  api.getRewardHistory.mockReset()
})
async function choose() {
  fireEvent.click(await screen.findByRole('button', { name: 'Redeem' }))
}
describe('reward redemption recovery', () => {
  it('browses older history without changing balances or redeeming points', async () => {
    const transactions = Array.from({ length: 50 }, (_, i) => ({ id: 'tx-' + i, description: 'Activity ' + i, points: -1, created_at: '2026-09-19T10:00:00Z' }))
    api.getRewards.mockResolvedValue({ ...wallet, transactions })
    api.getRewardHistory.mockRejectedValueOnce(new Error('Offline')).mockResolvedValueOnce([{ id: 'old', description: 'Older receipt', points: -5 }]).mockResolvedValueOnce(transactions)
    render(<AppRewards />)
    await screen.findByText('Activity 49')
    fireEvent.click(screen.getByRole('button', { name: 'Older activity' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('current page is unchanged')
    expect(screen.getByText('Activity 49')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Older activity' }))
    await screen.findByText('Older receipt')
    expect(api.getRewardHistory).toHaveBeenLastCalledWith('user-a', { id: 'tx-49', created_at: '2026-09-19T10:00:00Z' })
    expect(screen.getAllByText('100')).toHaveLength(2)
    expect(api.redeemReward).not.toHaveBeenCalled()
    fireEvent.click(screen.getByText('Show latest activity'))
    await screen.findByText('Activity 49')
    expect(api.getRewardHistory).toHaveBeenLastCalledWith('user-a', undefined)
  })
  it('retries initial loading failures without submitting a redemption', async () => {
    api.getRewards.mockRejectedValueOnce(new Error('Offline'))
    render(<AppRewards />)
    const retry = await screen.findByText('Retry rewards')
    fireEvent.click(retry)
    await screen.findByRole('button', { name: 'Redeem' })
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(api.getRewards).toHaveBeenCalledTimes(2)
    expect(api.redeemReward).not.toHaveBeenCalled()
  })
  it('waits for initial loading and blocks pending redemption during refresh', async () => {
    savePendingRedemption('user-a', { requestKey: 'retry-key', rewardId: 'perk-1', title: 'Museum perk', cost: 25 })
    let finishLoad
    api.getRewards.mockReturnValueOnce(new Promise((resolve, reject) => { finishLoad = reject }))
    render(<AppRewards />)
    expect(screen.getByText('Retry pending redemption')).toBeDisabled()
    await act(async () => { finishLoad(new Error('Offline')) })
    let finishRefresh
    api.getRewards.mockReturnValueOnce(new Promise((resolve) => { finishRefresh = resolve }))
    fireEvent.click(screen.getByText('Retry rewards'))
    fireEvent.click(screen.getByText('Retry rewards'))
    expect(screen.getByText('Retry pending redemption')).toBeDisabled()
    expect(api.getRewards).toHaveBeenCalledTimes(2)
    expect(api.redeemReward).not.toHaveBeenCalled()
    await act(async () => { finishRefresh(wallet) })
    expect(screen.getByText('Retry pending redemption')).toBeEnabled()
    expect(readPendingRedemption('user-a').requestKey).toBe('retry-key')
  })
  it('requires confirmation before spending points', async () => {
    render(<AppRewards />)
    await choose()
    expect(api.redeemReward).not.toHaveBeenCalled()
    fireEvent.click(screen.getByText('Cancel'))
    expect(api.redeemReward).not.toHaveBeenCalled()
  })
  it('retains the same request after an ambiguous failure and remount', async () => {
    api.redeemReward.mockRejectedValueOnce(new Error('Network interrupted'))
    const view = render(<AppRewards />)
    await choose()
    fireEvent.click(screen.getByText('Confirm redemption'))
    await screen.findByText('Network interrupted')
    const pending = readPendingRedemption('user-a')
    expect(pending.rewardId).toBe('perk-1')
    expect(readPendingRedemption('user-b')).toBeNull()
    view.unmount()
    render(<AppRewards />)
    await waitFor(() => expect(screen.getByText('Retry pending redemption')).toBeEnabled())
    fireEvent.click(screen.getByText('Retry pending redemption'))
    await screen.findByText(/Reference: receipt-1/)
    expect(api.redeemReward.mock.calls[0]).toEqual(api.redeemReward.mock.calls[1])
    expect(readPendingRedemption('user-a')).toBeNull()
  })
  it('does not send a request when persistent storage fails', async () => {
    render(<AppRewards />)
    await choose()
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage unavailable') })
    fireEvent.click(screen.getByText('Confirm redemption'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Storage unavailable')
    expect(api.redeemReward).not.toHaveBeenCalled()
  })
  it('keeps the receipt and disables spending when balance refresh fails', async () => {
    api.getRewards.mockResolvedValueOnce(wallet).mockRejectedValueOnce(new Error('offline'))
    render(<AppRewards />)
    await choose()
    fireEvent.click(screen.getByText('Confirm redemption'))
    await screen.findByText(/Reference: receipt-1/)
    expect(await screen.findByRole('alert')).toHaveTextContent('balance could not refresh')
    expect(screen.getByRole('button', { name: 'Redeem' })).toBeDisabled()
    api.getRewards.mockResolvedValue(wallet)
    fireEvent.click(screen.getByText('Refresh balance'))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Redeem' })).toBeEnabled())
    expect(api.redeemReward).toHaveBeenCalledTimes(1)
  })
  it('clears a request only after an explicit database rejection', async () => {
    api.redeemReward.mockRejectedValue({ code: 'P0001', message: 'Reward sold out' })
    render(<AppRewards />)
    await choose()
    fireEvent.click(screen.getByText('Confirm redemption'))
    await screen.findByText('Reward sold out')
    expect(readPendingRedemption('user-a')).toBeNull()
  })
})
