import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import Itineraries from './Itineraries'
import ProtectedRoute from '../auth/ProtectedRoute'

const api = vi.hoisted(() => ({ getItineraries: vi.fn(), getSavedContent: vi.fn(), createItinerary: vi.fn(), addItineraryItem: vi.fn(), removeItineraryItem: vi.fn(), deleteItinerary: vi.fn(), duplicateItinerary: vi.fn(), reorderItineraryStops: vi.fn(), updateItinerary: vi.fn(), updateStopNotes: vi.fn() }))
vi.mock('../lib/userData', () => api)
api.updateStopSchedule = vi.fn()
const calendar = vi.hoisted(() => ({ downloadItineraryCalendar: vi.fn() }))
vi.mock('../lib/itineraryCalendar', () => calendar)
const sharing = vi.hoisted(() => ({ setItinerarySharing: vi.fn() }))
vi.mock('../lib/itinerarySharing', () => sharing)
const auth = vi.hoisted(() => ({ user: { id: 'u1' }, loading: false }))
vi.mock('../auth/AuthContext', () => ({ useAuth: () => auth }))
vi.mock('../components/app/AppNav', () => ({ default: () => null }))
vi.mock('../components/PageShell', () => ({ default: ({ children }) => <main>{children}</main> }))

describe('itinerary editing', () => {
  afterEach(() => vi.unstubAllEnvs())
  beforeEach(() => {
    vi.resetAllMocks()
    auth.user = { id: 'u1' }
    auth.loading = false
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', itinerary_items: [{ id: 's1', title: 'Old stop', position: 7 }] }])
    api.getSavedContent.mockResolvedValue({ favorites: [{ id: 'p1', place_name: 'Downtown LA', place_external_id: 'downtown', place_snapshot: { category: 'Neighborhood' } }], events: [] })
  })
  async function open() { render(<Itineraries />); await screen.findByRole('heading', { name: 'Weekend' }) }
  it('uses the configured public website for share links', async () => {
    vi.stubEnv('VITE_PUBLIC_SITE_URL', 'https://forgepass.example')
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', is_public: true, share_token: 'token1', itinerary_items: [] }])
    await open()
    expect(screen.getByLabelText('Read-only sharing link')).toHaveValue('https://forgepass.example/shared-trip#token1')
  })
  it('blocks enabling a broken website link but still allows revocation', async () => {
    vi.stubEnv('VITE_PUBLIC_SITE_URL', 'invalid')
    await open()
    fireEvent.click(screen.getByText('Enable sharing link'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Website links are unavailable')
    expect(sharing.setItinerarySharing).not.toHaveBeenCalled()
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', is_public: true, share_token: 'token1', itinerary_items: [] }])
    fireEvent.click(screen.getByText('Refresh itineraries'))
    await screen.findByText('Turn off sharing')
    expect(screen.queryByLabelText('Read-only sharing link')).not.toBeInTheDocument()
    sharing.setItinerarySharing.mockResolvedValue({ id: 't1', is_public: false, share_token: 'token2' })
    fireEvent.click(screen.getByText('Turn off sharing'))
    await screen.findByText('Enable sharing link')
    expect(sharing.setItinerarySharing).toHaveBeenCalledWith(expect.objectContaining({ id: 't1' }), false)
  })
  it('shows only confirmed sharing links and removes them after revocation', async () => {
    sharing.setItinerarySharing.mockRejectedValueOnce(new Error('Sharing not confirmed'))
      .mockResolvedValueOnce({ id: 't1', is_public: true, share_token: 'token1' })
      .mockResolvedValueOnce({ id: 't1', is_public: true, share_token: 'token2' })
      .mockResolvedValueOnce({ id: 't1', is_public: false, share_token: 'token3' })
    await open()
    fireEvent.click(screen.getByText('Enable sharing link'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Sharing not confirmed')
    expect(screen.queryByLabelText('Read-only sharing link')).not.toBeInTheDocument()
    fireEvent.click(screen.getByText('Enable sharing link'))
    expect(await screen.findByLabelText('Read-only sharing link')).toHaveValue(`${window.location.origin}/shared-trip#token1`)
    fireEvent.click(screen.getByText('Replace sharing link'))
    await waitFor(() => expect(screen.getByLabelText('Read-only sharing link')).toHaveValue(`${window.location.origin}/shared-trip#token2`))
    fireEvent.click(screen.getByText('Turn off sharing'))
    await waitFor(() => expect(screen.queryByLabelText('Read-only sharing link')).not.toBeInTheDocument())
  })
  it('exports saved schedules, blocks exports during edits, and reports download failures', async () => {
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', itinerary_items: [{ id: 's1', title: 'Old stop', position: 0, starts_at: '2026-10-10T18:30:00Z' }] }])
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Schedule Old stop' }))
    expect(screen.getByText('Export calendar (.ics)')).toBeDisabled()
    fireEvent.click(screen.getByText('Cancel schedule'))
    calendar.downloadItineraryCalendar.mockImplementationOnce(() => { throw new Error('Download blocked') })
    fireEvent.click(screen.getByText('Export calendar (.ics)'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Download blocked')
    expect(screen.getByRole('heading', { name: 'Weekend' })).toBeInTheDocument()
    fireEvent.click(screen.getByText('Export calendar (.ics)'))
    await waitFor(() => expect(screen.queryByRole('alert')).not.toBeInTheDocument())
    expect(calendar.downloadItineraryCalendar).toHaveBeenLastCalledWith(expect.objectContaining({ id: 't1' }))
  })
  it('saves and clears visit times while protecting the open schedule from refresh and deletion', async () => {
    api.updateStopSchedule.mockResolvedValueOnce({ id: 's1', starts_at: '2026-10-10T18:30:00Z' }).mockResolvedValueOnce({ id: 's1', starts_at: null })
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Schedule Old stop' }))
    expect(screen.getByText('Refresh itineraries')).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Remove Old stop' })).toBeDisabled()
    expect(screen.getByText('Delete itinerary')).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Visit time for Old stop'), { target: { value: '2026-10-10T11:30' } })
    fireEvent.click(screen.getByText('Save visit time'))
    await screen.findByText('Edit visit time')
    expect(api.updateStopSchedule).toHaveBeenCalledWith('t1', expect.objectContaining({ id: 's1' }), new Date('2026-10-10T11:30').toISOString())
    fireEvent.click(screen.getByRole('button', { name: 'Schedule Old stop' }))
    fireEvent.change(screen.getByLabelText('Visit time for Old stop'), { target: { value: '' } })
    fireEvent.click(screen.getByText('Save visit time'))
    await screen.findByText('Time not scheduled')
    expect(api.updateStopSchedule).toHaveBeenLastCalledWith('t1', expect.objectContaining({ starts_at: '2026-10-10T18:30:00Z' }), null)
  })
  it('retains a failed schedule draft and allows canceling it', async () => {
    api.updateStopSchedule.mockRejectedValue(new Error('This stop schedule changed'))
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Schedule Old stop' }))
    fireEvent.change(screen.getByLabelText('Visit time for Old stop'), { target: { value: '2026-10-10T11:30' } })
    fireEvent.click(screen.getByText('Save visit time'))
    expect(await screen.findByRole('alert')).toHaveTextContent('schedule changed')
    expect(screen.getByLabelText('Visit time for Old stop')).toHaveValue('2026-10-10T11:30')
    fireEvent.click(screen.getByText('Cancel schedule'))
    expect(screen.getByText('Refresh itineraries')).toBeEnabled()
    expect(screen.getByText('Time not scheduled')).toBeInTheDocument()
  })
  it('retries failed itinerary loads without showing a misleading empty state or losing the creation draft', async () => {
    api.getItineraries.mockRejectedValueOnce(new Error('Offline'))
    render(<Itineraries />)
    fireEvent.change(screen.getByLabelText('Itinerary name'), { target: { value: 'Future trip' } })
    expect(await screen.findByRole('alert')).toHaveTextContent('Unable to load itineraries')
    expect(screen.queryByText(/No itineraries yet/)).not.toBeInTheDocument()
    expect(screen.getByText('Create itinerary')).toBeDisabled()
    fireEvent.click(screen.getByText('Retry itineraries'))
    await screen.findByRole('heading', { name: 'Weekend' })
    expect(screen.getByLabelText('Itinerary name')).toHaveValue('Future trip')
    expect(screen.getByText('Create itinerary')).toBeEnabled()
    expect(api.getItineraries).toHaveBeenCalledTimes(2)
    expect(api.getSavedContent).toHaveBeenCalledTimes(1)
  })
  it('keeps trips usable when saved content fails and retries without resetting trip edits', async () => {
    api.getSavedContent.mockRejectedValueOnce(new Error('Offline'))
    await open()
    expect(await screen.findByRole('alert')).toHaveTextContent('Unable to load saved places')
    expect(screen.getByLabelText('Saved place or event')).toBeDisabled()
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: 'Unsaved name' } })
    fireEvent.click(screen.getByText('Retry saved content'))
    await screen.findByRole('option', { name: 'Downtown LA (place)' })
    expect(screen.getByLabelText('Saved place or event')).toBeEnabled()
    expect(screen.getByLabelText('Edit itinerary name')).toHaveValue('Unsaved name')
    expect(api.getItineraries).toHaveBeenCalledTimes(1)
    expect(api.getSavedContent).toHaveBeenCalledTimes(2)
  })
  it('shows repeated retry failures and recovers to a confirmed empty account', async () => {
    api.getItineraries.mockRejectedValueOnce(new Error('Offline')).mockRejectedValueOnce(new Error('Still offline')).mockResolvedValueOnce([])
    render(<Itineraries />)
    fireEvent.click(await screen.findByText('Retry itineraries'))
    fireEvent.click(await screen.findByText('Retry itineraries'))
    await screen.findByText(/No itineraries yet/)
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(api.getItineraries).toHaveBeenCalledTimes(3)
  })
  function guardedPage() {
    return <MemoryRouter initialEntries={['/app/itineraries']}><Routes>
      <Route path="/app/itineraries" element={<ProtectedRoute><Itineraries /></ProtectedRoute>} />
      <Route path="/auth" element={<p>Sign in</p>} />
    </Routes></MemoryRouter>
  }
  it('clears account data and pending note drafts on account switch, ignoring old saves', async () => {
    let finishSave
    api.updateStopNotes.mockReturnValue(new Promise((resolve) => { finishSave = resolve }))
    const view = render(guardedPage())
    await screen.findByRole('heading', { name: 'Weekend' })
    fireEvent.click(screen.getByRole('button', { name: 'Edit notes for Old stop' }))
    fireEvent.change(screen.getByLabelText('Notes for Old stop'), { target: { value: 'Private instructions' } })
    fireEvent.click(screen.getByText('Save notes'))
    api.getItineraries.mockResolvedValue([{ id: 't2', name: 'New account trip', itinerary_items: [] }])
    auth.user = { id: 'u2' }
    view.rerender(guardedPage())
    expect(screen.queryByRole('heading', { name: 'Weekend' })).not.toBeInTheDocument()
    expect(screen.queryByDisplayValue('Private instructions')).not.toBeInTheDocument()
    await screen.findByRole('heading', { name: 'New account trip' })
    await act(async () => { finishSave({ id: 's1', notes: 'Private instructions' }) })
    expect(screen.queryByText('Private instructions')).not.toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'New account trip' })).toBeInTheDocument()
    expect(api.getItineraries).toHaveBeenLastCalledWith('u2')
  })
  it('preserves drafts when the session refreshes for the same account', async () => {
    const view = render(guardedPage())
    await screen.findByRole('heading', { name: 'Weekend' })
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: 'Unsaved trip' } })
    auth.user = { id: 'u1', email: 'refreshed@example.com' }
    view.rerender(guardedPage())
    expect(screen.getByLabelText('Edit itinerary name')).toHaveValue('Unsaved trip')
    expect(api.getItineraries).toHaveBeenCalledTimes(1)
  })
  it('removes private itinerary content on sign-out', async () => {
    const view = render(guardedPage())
    await screen.findByRole('heading', { name: 'Weekend' })
    auth.user = null
    view.rerender(guardedPage())
    await screen.findByText('Sign in')
    expect(screen.queryByRole('heading', { name: 'Weekend' })).not.toBeInTheDocument()
    expect(screen.queryByText('1. Old stop')).not.toBeInTheDocument()
  })
  it('saves stop notes and clears them without changing the stop', async () => {
    api.updateStopNotes.mockResolvedValueOnce({ id: 's1', notes: 'Bring tickets\nMeet at noon' }).mockResolvedValueOnce({ id: 's1', notes: null })
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Edit notes for Old stop' }))
    expect(screen.getByRole('button', { name: 'Remove Old stop' })).toBeDisabled()
    expect(screen.getByText('Delete itinerary')).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Notes for Old stop'), { target: { value: 'Bring tickets\nMeet at noon' } })
    fireEvent.click(screen.getByText('Save notes'))
    await screen.findByText('Bring tickets Meet at noon')
    expect(api.updateStopNotes).toHaveBeenCalledWith('t1', expect.objectContaining({ id: 's1' }), 'Bring tickets\nMeet at noon')
    expect(screen.getByText('1. Old stop')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Edit notes for Old stop' }))
    expect(screen.getByLabelText('Notes for Old stop')).toHaveValue('Bring tickets\nMeet at noon')
    fireEvent.change(screen.getByLabelText('Notes for Old stop'), { target: { value: '' } })
    fireEvent.click(screen.getByText('Save notes'))
    await waitFor(() => expect(screen.queryByText('Save notes')).not.toBeInTheDocument())
    expect(screen.queryByText('Bring tickets Meet at noon')).not.toBeInTheDocument()
  })
  it('preserves failed note drafts and discards canceled notes', async () => {
    api.updateStopNotes.mockRejectedValue(new Error('This stop changed'))
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Edit notes for Old stop' }))
    fireEvent.change(screen.getByLabelText('Notes for Old stop'), { target: { value: 'Draft note' } })
    fireEvent.click(screen.getByText('Save notes'))
    expect(await screen.findByRole('alert')).toHaveTextContent('This stop changed')
    expect(screen.getByLabelText('Notes for Old stop')).toHaveValue('Draft note')
    fireEvent.click(screen.getByText('Cancel notes'))
    fireEvent.click(screen.getByRole('button', { name: 'Edit notes for Old stop' }))
    expect(screen.getByLabelText('Notes for Old stop')).toHaveValue('')
    expect(api.updateStopNotes).toHaveBeenCalledTimes(1)
  })
  it('saves renamed and dated trips while retaining stops', async () => {
    api.updateItinerary.mockResolvedValue({ id: 't1', name: 'Vacation', starts_on: '2026-10-10', ends_on: null })
    await open()
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: ' Vacation ' } })
    fireEvent.change(screen.getByLabelText('Edit start date'), { target: { value: '2026-10-10' } })
    fireEvent.click(screen.getByText('Save trip details'))
    await screen.findByRole('heading', { name: 'Vacation' })
    expect(api.updateItinerary).toHaveBeenCalledWith(expect.objectContaining({ id: 't1', name: 'Weekend' }), { name: 'Vacation', starts_on: '2026-10-10', ends_on: null })
    expect(screen.getByText('1. Old stop')).toBeInTheDocument()
    expect(screen.queryByText('Save trip details')).not.toBeInTheDocument()
  })
  it('preserves the draft and original display when saving fails', async () => {
    api.updateItinerary.mockRejectedValue(new Error('Trip changed. Reload before editing.'))
    await open()
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: 'Vacation' } })
    fireEvent.click(screen.getByText('Save trip details'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Trip changed')
    expect(screen.getByRole('heading', { name: 'Weekend' })).toBeInTheDocument()
    expect(screen.getByLabelText('Edit itinerary name')).toHaveValue('Vacation')
    expect(screen.getByText('Save trip details')).toBeEnabled()
  })
  it('discards canceled edits and allows clearing existing dates', async () => {
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', starts_on: '2026-10-10', ends_on: '2026-10-11', itinerary_items: [] }])
    api.updateItinerary.mockResolvedValue({ id: 't1', name: 'Weekend', starts_on: null, ends_on: null })
    await open()
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: 'Discard me' } })
    fireEvent.click(screen.getByText('Cancel editing'))
    expect(api.updateItinerary).not.toHaveBeenCalled()
    fireEvent.click(screen.getByText('Edit trip details'))
    expect(screen.getByLabelText('Edit itinerary name')).toHaveValue('Weekend')
    fireEvent.change(screen.getByLabelText('Edit start date'), { target: { value: '' } })
    fireEvent.change(screen.getByLabelText('Edit end date'), { target: { value: '' } })
    fireEvent.click(screen.getByText('Save trip details'))
    await waitFor(() => expect(screen.queryByText('Save trip details')).not.toBeInTheDocument())
    expect(api.updateItinerary).toHaveBeenCalledWith(expect.anything(), { name: 'Weekend', starts_on: null, ends_on: null })
  })
  it('rejects whitespace names and reversed dates in the editor', async () => {
    await open()
    fireEvent.click(screen.getByText('Edit trip details'))
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: '   ' } })
    fireEvent.click(screen.getByText('Save trip details'))
    expect(screen.getByRole('alert')).toHaveTextContent('Enter an itinerary name')
    fireEvent.change(screen.getByLabelText('Edit itinerary name'), { target: { value: 'Trip' } })
    fireEvent.change(screen.getByLabelText('Edit start date'), { target: { value: '2026-10-10' } })
    fireEvent.change(screen.getByLabelText('Edit end date'), { target: { value: '2026-10-09' } })
    fireEvent.click(screen.getByText('Save trip details'))
    expect(screen.getByRole('alert')).toHaveTextContent('End date must be on or after')
    expect(api.updateItinerary).not.toHaveBeenCalled()
  })
  it('adds a returned copy while retaining the original', async () => {
    api.duplicateItinerary.mockResolvedValue({ id: 't2', name: 'Weekend (copy)', itinerary_items: [] })
    await open()
    fireEvent.click(screen.getByText('Duplicate itinerary'))
    await screen.findByRole('heading', { name: 'Weekend (copy)' })
    expect(screen.getByRole('heading', { name: 'Weekend' })).toBeInTheDocument()
    expect(api.duplicateItinerary).toHaveBeenCalledWith('t1')
  })
  it('does not display a copy when the database rejects duplication', async () => {
    api.duplicateItinerary.mockRejectedValue(new Error('Itinerary unavailable'))
    await open()
    fireEvent.click(screen.getByText('Duplicate itinerary'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Itinerary unavailable')
    expect(screen.queryByRole('heading', { name: 'Weekend (copy)' })).not.toBeInTheDocument()
  })
  function twoStops() {
    api.getItineraries.mockResolvedValue([{ id: 't1', name: 'Weekend', itinerary_items: [
      { id: 's1', title: 'First stop', position: 0 }, { id: 's2', title: 'Second stop', position: 1 },
    ] }])
  }
  it('persists a move before displaying its new order', async () => {
    twoStops()
    await open()
    fireEvent.click(screen.getByText('Plan trip directions'))
    fireEvent.change(screen.getByLabelText('Destination 1: First stop'), { target: { value: 'Temporary address' } })
    expect(screen.getByRole('button', { name: 'Move First stop up' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Move Second stop up' }))
    await screen.findByText('1. Second stop')
    expect(api.reorderItineraryStops).toHaveBeenCalledWith('t1', ['s1', 's2'], ['s2', 's1'])
    expect(screen.getByRole('button', { name: 'Move First stop down' })).toBeDisabled()
    expect(screen.queryByDisplayValue('Temporary address')).not.toBeInTheDocument()
    fireEvent.click(screen.getByText('Plan trip directions'))
    const route = new URL(screen.getByRole('link', { name: 'Open route 1 (stops 1–2)' }).href)
    expect(route.searchParams.get('waypoints')).toBe('Second stop')
    expect(route.searchParams.get('destination')).toBe('First stop')
  })
  it('keeps the prior order after a concurrent change rejection', async () => {
    twoStops()
    api.reorderItineraryStops.mockRejectedValue(new Error('Trip changed. Reload before reordering.'))
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Move First stop down' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Trip changed')
    expect(screen.getByText('1. First stop')).toBeInTheDocument()
  })
  it('imports saved places while preserving their source and append order', async () => {
    api.addItineraryItem.mockResolvedValue({ id: 's2', title: 'Downtown LA', position: 8 })
    await open()
    fireEvent.change(screen.getByLabelText('Saved place or event'), { target: { value: 'place:p1' } })
    fireEvent.click(screen.getByText('Add saved stop'))
    await screen.findByRole('button', { name: 'Remove Downtown LA' })
    expect(api.addItineraryItem).toHaveBeenCalledWith('t1', 'Downtown LA', 8, expect.objectContaining({ item_type: 'place', external_id: 'downtown' }))
  })
  it('keeps a stop visible if deletion fails', async () => {
    api.removeItineraryItem.mockRejectedValue(new Error('Connection lost'))
    await open()
    fireEvent.click(screen.getByRole('button', { name: 'Remove Old stop' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Connection lost')
    expect(screen.getByText('1. Old stop')).toBeInTheDocument()
  })
  it('requires confirmation before deleting a trip', async () => {
    await open()
    fireEvent.click(screen.getByText('Delete itinerary'))
    expect(api.deleteItinerary).not.toHaveBeenCalled()
    fireEvent.click(screen.getByText('Confirm deletion'))
    await waitFor(() => expect(screen.queryByRole('heading', { name: 'Weekend' })).not.toBeInTheDocument())
    expect(api.deleteItinerary).toHaveBeenCalledWith('t1')
  })
  it('keeps an unconfirmed deletion visible and reconciles it through refresh', async () => {
    api.deleteItinerary.mockRejectedValue(new Error('Refresh itineraries to check its status.'))
    await open()
    fireEvent.click(screen.getByText('Delete itinerary'))
    fireEvent.click(screen.getByText('Confirm deletion'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Refresh itineraries')
    expect(screen.getByRole('heading', { name: 'Weekend' })).toBeInTheDocument()
    api.getItineraries.mockResolvedValue([])
    fireEvent.click(screen.getByText('Refresh itineraries'))
    await waitFor(() => expect(screen.queryByRole('heading', { name: 'Weekend' })).not.toBeInTheDocument())
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(api.deleteItinerary).toHaveBeenCalledTimes(1)
  })
  it('protects open edits from refresh and keeps trips after a refresh failure', async () => {
    await open()
    fireEvent.click(screen.getByText('Edit trip details'))
    expect(screen.getByText('Refresh itineraries')).toBeDisabled()
    fireEvent.click(screen.getByText('Cancel editing'))
    api.getItineraries.mockRejectedValue(new Error('Offline'))
    fireEvent.click(screen.getByText('Refresh itineraries'))
    expect(await screen.findByRole('alert')).toHaveTextContent('Offline')
    expect(screen.getByRole('heading', { name: 'Weekend' })).toBeInTheDocument()
    expect(screen.getByText('Refresh itineraries')).toBeEnabled()
  })
  it('rejects reversed trip dates before saving', async () => {
    await open()
    fireEvent.change(screen.getByLabelText('Itinerary name'), { target: { value: 'Trip' } })
    fireEvent.change(screen.getByLabelText('Start date'), { target: { value: '2026-10-10' } })
    fireEvent.change(screen.getByLabelText('End date'), { target: { value: '2026-10-09' } })
    fireEvent.click(screen.getByText('Create itinerary'))
    expect(screen.getByRole('alert')).toHaveTextContent('End date must be on or after')
    expect(api.createItinerary).not.toHaveBeenCalled()
  })
})
